spring.application.name=agricultor

spring.datasource.url=jdbc:postgresql://db-cafetito:5432/DB_Cafetito?currentSchema=agricultor
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8082

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=agricultor
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

jwt.secret=cafetitoSecretKey_SUPER_SEGURA_2026_con_mas_de_256_bits_123456789