spring.application.name=beneficio-service

# Base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://db-cafetito:5432/DB_Cafetito?currentSchema=beneficio
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Puerto
server.port=8083

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=beneficio

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# JWT (misma clave que usa el microservicio login)
jwt.secret=cafetitoSecretKey_SUPER_SEGURA_2026_con_mas_de_256_bits_123456789
